services:
  oauth-server:
    image: php:alpine
    volumes:
      - ./oauth-server:/home/root
    working_dir: /home/root
    ports:
      - 8081:8081
    command: "php -S 0.0.0.0:8081"

  oauth-client:
    build: ./oauth-client
    volumes:
      - ./oauth-client:/home/root
    working_dir: /home/root
    ports:
      - 80:80
      - 443:443
